"""
update_config.py — Recompute derived values in config.yaml.

Edit the base params (cart, link1, link2, physics, integrator) then run:

    python update_config.py

The `derived` section will be updated automatically.
"""

import yaml
from pathlib import Path

CONFIG = Path(__file__).parent / 'config.yaml'

# Template preserves the hand-edited comment style.
_TEMPLATE = """\
cart:
  mass: {M}        # M (kg)

link1:
  mass: {m1}       # m1 (kg)
  length: {l1}     # l1 (m)

link2:
  mass: {m2}       # m2 (kg)
  length: {l2}     # l2 (m)

physics:
  g: {g}           # gravitational acceleration (m/s^2)

integrator:
  dt: {dt}         # timestep (s)

# ── auto-computed ─────────────────────────────────────────────────────────────
# Regenerated by:  python update_config.py
derived:
  I1:        {I1}      # m1 * l1^2 / 12  (kg·m²)
  I2:        {I2}      # m2 * l2^2 / 12  (kg·m²)
  sample_hz: {sample_hz}      # 1 / dt           (Hz)
"""


def main():
    with open(CONFIG) as f:
        cfg = yaml.safe_load(f)

    M  = cfg['cart']['mass']
    m1 = cfg['link1']['mass']
    l1 = cfg['link1']['length']
    m2 = cfg['link2']['mass']
    l2 = cfg['link2']['length']
    g  = cfg['physics']['g']
    dt = cfg['integrator']['dt']

    I1        = round(m1 * l1 ** 2 / 12, 6)
    I2        = round(m2 * l2 ** 2 / 12, 6)
    sample_hz = round(1.0 / dt)

    content = _TEMPLATE.format(
        M=M, m1=m1, l1=l1, m2=m2, l2=l2, g=g, dt=dt,
        I1=I1, I2=I2, sample_hz=sample_hz,
    )

    with open(CONFIG, 'w') as f:
        f.write(content)

    print("config.yaml updated:")
    print(f"  I1        = {I1} kg·m²  (m1*l1²/12)")
    print(f"  I2        = {I2} kg·m²  (m2*l2²/12)")
    print(f"  sample_hz = {sample_hz} Hz    (1/dt)")


if __name__ == '__main__':
    main()
